"""empty message

Revision ID: 3b84508421bf
Revises: 04193d204ff2
Create Date: 2021-11-12 16:06:13.492572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b84508421bf'
down_revision = '04193d204ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_table', sa.Column('password', sa.String(), nullable=True))
    op.add_column('info_table', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_table', 'email')
    op.drop_column('info_table', 'password')
    # ### end Alembic commands ###
