"""empty message

Revision ID: f6e5adf4af31
Revises: 3b84508421bf
Create Date: 2021-11-12 17:47:30.356796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e5adf4af31'
down_revision = '3b84508421bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'info_table', ['email'])
    op.create_unique_constraint(None, 'info_table', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'info_table', type_='unique')
    op.drop_constraint(None, 'info_table', type_='unique')
    # ### end Alembic commands ###
